
- name: Check if Upstarts configuration directory exists
  stat: path="/etc/init/"
  register: upstart_existance

- name: Install Upstart configuration
  template: src="upstart-config.tmpl" dest="/etc/init/{{ tendenci_install_name }}}.conf"
  when: upstart_existance.stat.exists


- name: Check if Systemd configuration directory exists
  stat: path="/etc/systemd/system/"
  register: systemd_existance

- name: Install Systemd configuration
  template: src="systemd-config.tmpl" dest="/etc/systemd/system/{{ tendenci_install_name }}.service"
  when: systemd_existance.stat.exists


- name: Enable Tendenci service
  service: name="{{ tendenci_install_name }}" enabled=yes

- name: Start Tendenci service
  service: name="{{ tendenci_install_name }}" state=started

