---
# tasks file for tendenci

- include: install_tendenci.yml
- include: update_local_settings_file.yml
- include: create_superuser.yml

- include: custom_themes.yml
  when: tendenci_custom_theme_name != ''

- include: configure_init_systems.yml

